name: Test Action

on:
  push:
    branches: [ master ]

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch data
      uses: ./
      with:
        file: 'testfile.json'
        url: 'http://wave.webaim.org/api/request?key=uYC6ghs23017&url=https://nice-stone-00b25ea03.2.azurestaticapps.net/'