name: Fetch API
on:
  push:
    branches:
      - main
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: http://wave.webaim.org/api/request?key=uYC6ghs23017&url=https://nice-stone-00b25ea03.2.azurestaticapps.net/
          SAVE_LOCATION: public
          BRANCH: master


      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: public/data.json