on:
 push:
   tags:
     - '**'
 
jobs:
 run-updater:
   runs-on: ubuntu-latest
   steps:
   - name: REST API with curl
     run: |
       curl -X GET "http://wave.webaim.org/api/request?key=uYC6ghs23017&url=https://nice-stone-00b25ea03.2.azurestaticapps.net/"
